### ISSUE TITLE
standard lib

### ISSUE THREAD

**Issue by chenl** [cbytensky/imperva#2]
Can you implement this by only using the standard libraries, if we rephrase the problem to use only the standard libraries in production, while permitting packages from pypi for development dependencies only, e.g. unit-testing / formatting / mocking, etc.?

**Comment by cbytensky** [comment]
Reimplemented without `networkx`. Used simple brute-force algo, with _O_(_n_<sup>2</sup>) complexity.

_O_(_n_) complexity needs Johnson’s algo (with Tarjan’s algo for strongly connected components).
